### ISSUE TITLE
怎么隐藏状态栏中的 Search Engine: Google

### ISSUE THREAD

**Issue by younger-1** [Wscats/search-online#2]
我只想隐藏 Search Engine，而不隐藏状态栏右边的翻译部分

**Comment by Wscats** [comment]
> 我只想隐藏 Search Engine，而不隐藏状态栏右边的翻译部分

暂无开关隐藏，我下一个版本尽量尝试增加开关去隐藏 `Search Engine` 设置项。

**Comment by Wscats** [comment]
你好，现在已支持该功能，现在默认关闭离线词典，如果要开启，只需做以下配置：
```json
{
  "search-online.show-status-bar": true
}
```

**Comment by younger-1** [comment]
> 
> 
> 你好，现在已支持该功能，现在默认关闭离线词典，如果要开启，只需做以下配置：
> 
> ```json
> {
>   "search-online.show-status-bar": true
> }
> ```

Great work!
