### ISSUE TITLE
Improve startup time

### ISSUE THREAD

**Issue by marblewraith** [Wscats/search-online#4]
I do not know the reason why, but on average this extension takes about +200ms to load.

This is alot of time for an extension that shouldn't actually require parsing anything other than a few settings at startup.

![startupSearch](https://user-images.githubusercontent.com/45786628/102951970-295b8380-4522-11eb-8efd-2930849d1cd2.PNG)

**Comment by Wscats** [comment]
Thank you for your suggestion. Since it will load a relatively large local dictionary during initialization, it may slow down. I will optimize it later, thank you.

**Comment by Wscats** [comment]
Hello, I have fixed this problem. The plugin now supports lazy loading, and the startup speed will be faster.

**Comment by marblewraith** [comment]
It's much better! Cold activation time has halved to ~100ms.

Is there any way to make it faster still?

There's an error you can see in the screenshot above. I'll make a separate issue for it, could that be what's responsible for slowing things down?

Awesome work. Super Impressed!
